import os
import json
from google import genai
from dotenv import load_dotenv
load_dotenv()
client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)
def generate_portfolio_html(
    resume_data: dict,
    portfolio_style: str
):
    prompt = f"""
You are an expert portfolio website generator.
Generate a complete single-page portfolio website.
IMPORTANT RULES:
- Use ONLY information present in the resume data.
- Do NOT invent job titles.
- Do NOT invent skills.
- Do NOT invent projects.
- Do NOT invent descriptions.
- If information is missing, leave the section minimal.
Return ONLY raw HTML.
Requirements:
- Single HTML file
- Embedded CSS
- Responsive
- Modern startup-quality design
- Dark/light mode toggle
- Smooth scrolling
- Professional typography
Portfolio Style:
{portfolio_style}
Resume Data:
{json.dumps(resume_data, indent=2)}
IMPORTANT:
Return only the HTML document.
Start directly with:
<!DOCTYPE html>
"""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        print("\n===== GEMINI PORTFOLIO RESPONSE =====")
        print(response)
        print("=====================================\n")
        print("\n===== RESPONSE TEXT =====")
        print(response.text)
        print("=========================\n")
        if not response.text:
            print("No HTML generated by Gemini.")
            return "NO_HTML_GENERATED"
        html = response.text.strip()
        html = html.replace("```html", "")
        html = html.replace("```", "")
        return html
    except Exception as e:
        print("\n===== PORTFOLIO GENERATION ERROR =====")
        print(str(e))
        print("======================================\n")
        raise e